COMP: Fix `SpatialObject` module refactoring-derived errors
Fix `SpatialObject` module refactoring-derived errors.

Fixes:
```
/Users/Kitware/Dashboards/TestsModules/Remote/LesionSizingToolkit/include/itkLandmarksReader.h:80:55:
error: no type named 'SceneType' in 'itk::SpatialObjectReader<3, unsigned
short, itk::DefaultStaticMeshTraits<unsigned short, 3, 3, float, float,
unsigned short> >'
  using SceneType = typename SpatialObjectReaderType::SceneType;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
```

and
```
/Users/Kitware/Dashboards/TestsModules/Remote/LesionSizingToolkit/include/itkConnectedThresholdSegmentationModule.hxx:81:58:
error: no type named 'PointListType' in 'itk::LandmarkSpatialObject<3>'
  using PointListType = typename InputSpatialObjectType::PointListType;
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
```

raised at:
http://testing.cdash.org/viewBuildError.php?buildid=5854571

and stemming from the changes introduced in:
https://github.com/InsightSoftwareConsortium/ITK/pull/613/commits/a1a98aa1f361b7a5ea3d431f9f28a1263dedca2d

and
https://github.com/InsightSoftwareConsortium/ITK/commit/747bb86eeb64bc08ffcaa9b0beb357bf87e01a9b

And other errors stemming from
https://github.com/InsightSoftwareConsortium/ITK/pull/613